[book]
title = "ArcheAge Addon Documentation"
authors = ["Noviern"]
language = "en"
src = "docs"

[output.html.fold]
enable = true
level  = 1

[output.html.search]
heading-split-level = 4

[build]
create-missing = false